name: 'GitHub Action for Build'
description: 'Build docker image'
inputs:
  args:
    description: 'buildtool arguments, see https://buildtools.io/commands/#build for information'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.args }}
branding:
  icon: 'package'
  color: 'green'